# Generated by Django 5.0.6 on 2024-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("family_members", "0001_initial"),
        ("medicaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="medicaments",
            field=models.ManyToManyField(
                blank=True,
                related_name="family_members",
                through="medicaments.FamilyMedicine",
                to="medicaments.medicine",
            ),
        ),
        migrations.AddField(
            model_name="familymember",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
