# Generated by Django 5.0.6 on 2024-07-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("allergy_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergies", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="FamilyAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allergies.allergy",
                    ),
                ),
            ],
            options={
                "db_table": "family_allergies",
            },
        ),
    ]
