# Generated by Django 5.0.6 on 2024-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergies",
            fields=[
                ("allergy_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergies", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "allergy",
            },
        ),
    ]
