# Generated by Django 5.0.6 on 2024-07-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("Medicament_id", models.AutoField(primary_key=True, serialize=False)),
                ("medicament", models.CharField(max_length=50)),
                ("for_what", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("costs", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dose", models.IntegerField()),
                ("when_to_use", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "medicaments",
            },
        ),
        migrations.CreateModel(
            name="FamilyMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Medicament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicaments.medicine",
                    ),
                ),
            ],
            options={
                "db_table": "family-m edicine",
            },
        ),
    ]
