# Generated by Django 5.0.6 on 2024-07-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("disease_id", models.AutoField(primary_key=True, serialize=False)),
                ("disease", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "diseases",
            },
        ),
        migrations.CreateModel(
            name="FamilyDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diseases.disease",
                    ),
                ),
            ],
            options={
                "db_table": "family_diseases",
            },
        ),
    ]
