# Generated by Django 5.0.6 on 2024-07-07 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operations",
            fields=[
                ("operation_id", models.AutoField(primary_key=True, serialize=False)),
                ("operation", models.CharField(max_length=50)),
                ("doctor", models.CharField(verbose_name=30)),
                ("date", models.IntegerField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "costs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operations",
            },
        ),
    ]
