# Generated by Django 5.0.6 on 2024-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operations",
            name="doctor",
            field=models.CharField(max_length=30),
        ),
    ]
