# Generated by Django 5.0.6 on 2024-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_speciality", models.CharField(max_length=50)),
                ("doctor_name", models.CharField(max_length=50)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("appointment_address", models.CharField(max_length=50)),
                ("accompany", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "appointments",
            },
        ),
    ]
